#!/usr/bin/env python3
"""Deterministic generator for a wiki's `wiki/index.md`.

Rebuilding the index was the single most token-hungry bookkeeping step in
INGEST: the agent used to read every page to reconstruct the tables by hand.
This script derives the exact same catalog straight from page frontmatter and
body `## Sources` links, so the agent's only job is to call it.

Usage:
    wiki_index.py <wiki-root> [--write | --check] [--json]

- `--write` regenerates wiki/index.md in place.
- `--check` compares the current index.md against the generated content and
  exits 1 on drift (used by LINT; no file is modified).
- With neither flag, prints the generated index to stdout.

Exit codes:
    0 — ok (or up to date on --check)
    1 — drift detected on --check, or index.md missing
    2 — usage / path error
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import wiki_lib


def table_rows(wiki_dir: Path, folder: str, pages: dict[str, Path]) -> list[list[str]]:
    rows = []
    for key in sorted(k for k in pages if k.startswith(f"{folder}/")):
        page = pages[key]
        meta, body = wiki_lib.read_page(page)
        name = key.rsplit("/", 1)[1]
        link = f"[{wiki_lib.title_for(meta, name)}]({key})"
        description = "—" if not wiki_lib.description_for(meta) else wiki_lib.description_for(meta)
        sources = str(wiki_lib.count_sources_in_body(body, key, pages))
        updated = wiki_lib.meta_value(meta, "updated", "created")
        rows.append([link, description, sources, updated])
    return rows


def build_index(wiki_dir: Path) -> str:
    """The full markdown index for the wiki, regenerated from disk state."""
    pages = wiki_lib.collect_pages(wiki_dir)
    groups = []
    for folder, heading in (("entities", "Entities"), ("concepts", "Concepts"), ("sources", "Sources")):
        rows = table_rows(wiki_dir, folder, pages)
        if not rows:
            continue
        groups.append(f"## {heading} ({len(rows)})\n\n")
        groups.append("| Page | Description | Sources | Updated |\n")
        groups.append("|---|---|---|---|\n")
        for link, description, sources, updated in rows:
            groups.append(f"| {link} | {description} | {sources} | {updated} |\n")
        groups.append("\n")

    parts = [
        "# Index\n",
        "_Generated by `wiki_index.py`. Do not edit by hand — re-run the script after any change to wiki pages._\n",
        "",
        "## Overview\n",
        f"* [Overview](overview.md) — evolving synthesis of the wiki's knowledge\n",
        "",
    ]
    parts.extend(groups)
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("wiki_root", type=Path, help="Path to the wiki root (contains wiki/ and raw/)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="regenerate wiki/index.md")
    mode.add_argument("--check", action="store_true", help="verify wiki/index.md is up to date")
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    args = parser.parse_args()

    root = args.wiki_root.expanduser().resolve()
    wiki_dir = root / "wiki"
    if not wiki_dir.is_dir():
        if args.json:
            print(json.dumps({"ok": False, "reason": f"missing wiki/ directory under {root}"}))
        else:
            print(f"error: missing wiki/ directory under {root}", file=sys.stderr)
        return 2

    generated = build_index(wiki_dir)
    index_path = wiki_dir / "index.md"

    if args.check:
        if not index_path.is_file():
            if args.json:
                print(json.dumps({"ok": False, "drift": True, "reason": "index.md missing"}))
            else:
                print("DRIFT: wiki/index.md is missing (run wiki_index.py --write)")
            return 1
        current = index_path.read_text(encoding="utf-8", errors="replace")
        if current == generated:
            if args.json:
                print(json.dumps({"ok": True, "drift": False}))
            else:
                print("OK: wiki/index.md is up to date")
            return 0
        if args.json:
            print(json.dumps({"ok": False, "drift": True, "reason": "index.md differs from generated content"}))
        else:
            print("DRIFT: wiki/index.md is out of date (run wiki_index.py --write)")
        return 1

    if args.write:
        index_path.parent.mkdir(parents=True, exist_ok=True)
        index_path.write_text(generated, encoding="utf-8")
        if args.json:
            print(json.dumps({"ok": True, "wrote": str(index_path)}))
        else:
            print(f"wrote {index_path}")
        return 0

    print(generated, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())